jwt:
    secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArrNumberSym$^@GHJ@YUH@HQH'
server:
    port: 8081
spring:
    datasource:
        password: 123456
        url: jdbc:mysql://localhost:3306/graduation_thesis_server
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true
